wordpressUsername: root
wordpressBlogName: Root's Blog!
persistence:
  enabled: true
  storageClass: "rook-ceph-block"
  accessMode: ReadWriteOnce
  size: 10Gi
  master:
    persistence:
      enabled: true
      storageClass: "rook-ceph-block"
      accessModes:
        - ReadWriteOnce
      size: 8Gi

