apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: awx
    role: web
  name: awx-lb
spec:
  ports:
  - port: 8052
    protocol: TCP
    targetPort: 8052
  selector:
    app: awx
    role: web
  type: LoadBalancer
status:
  loadBalancer: {}
