apiVersion: v1
entries:
  jenkins:
  - apiVersion: v1
    appVersion: lts
    created: "2020-04-15T21:27:13.839262+01:00"
    description: Open source continuous integration server. It supports multiple SCM
      tools including CVS, Subversion and Git. It can execute Apache Ant and Apache
      Maven-based projects as well as arbitrary scripts.
    digest: e2929f9afd62dc4cdad8ab8bbb93a7f6ec934b82152afac077140ed6a9aa64e0
    home: https://jenkins.io/
    icon: https://wiki.jenkins-ci.org/download/attachments/2916393/logo.png
    maintainers:
    - email: lachlan.evenson@microsoft.com
      name: lachie83
    - email: viglesias@google.com
      name: viglesiasce
    - email: maor.friedman@redhat.com
      name: maorfr
    - email: mail@torstenwalter.de
      name: torstenwalter
    - email: garridomota@gmail.com
      name: mogaal
    name: jenkins
    sources:
    - https://github.com/jenkinsci/jenkins
    - https://github.com/jenkinsci/docker-jnlp-slave
    - https://github.com/maorfr/kube-tasks
    - https://github.com/jenkinsci/configuration-as-code-plugin
    urls:
    - jenkins-1.12.0.tgz
    version: 1.12.0
  wordpress:
  - apiVersion: v1
    appVersion: 5.3.2
    created: "2020-04-15T21:27:13.844523+01:00"
    dependencies:
    - condition: mariadb.enabled
      name: mariadb
      repository: https://kubernetes-charts.storage.googleapis.com/
      tags:
      - wordpress-database
      version: 7.x.x
    deprecated: true
    description: DEPRECATED Web publishing platform for building blogs and websites.
    digest: 464781b6f4d8457c3cd170d5ac67257283252880c2fcbfbef85a0775729ec971
    home: http://www.wordpress.com/
    icon: https://bitnami.com/assets/stacks/wordpress/img/wordpress-stack-220x234.png
    keywords:
    - wordpress
    - cms
    - blog
    - http
    - web
    - application
    - php
    name: wordpress
    sources:
    - https://github.com/bitnami/bitnami-docker-wordpress
    urls:
    - wordpress-9.0.3.tgz
    version: 9.0.3
generated: "2020-04-15T21:27:13.834533+01:00"
